on: [push, pull_request]
name: Build and Test check
jobs:
  rp2040-hal-builds:
    name: Build rp2040-hal's features
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Build rp2040-hal
        run: cd rp2040-hal && cargo hack build --optional-deps --each-feature --target=thumbv6m-none-eabi
      - name: Build rp2040-hal-macros
        run: cd rp2040-hal-macros && cargo hack build --optional-deps --each-feature
      - name: Build on-target-tests
        run: cd on-target-tests && cargo hack build --optional-deps --each-feature
      - name: Build rp2040-hal-examples
        run: cd rp2040-hal-examples && cargo hack build --optional-deps --each-feature
  tests:
    name: Execute host-runable tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Test
        run: cd rp2040-hal && cargo hack test --optional-deps --each-feature --tests --features critical-section-impl
      - name: Test docs
        run: cd rp2040-hal && cargo hack test --optional-deps --each-feature --doc --features critical-section-impl
      - name: Test macros
        run: cd rp2040-hal-macros && cargo hack test --optional-deps --tests --each-feature
      - name: Test macro docs
        run: cd rp2040-hal-macros && cargo hack test --optional-deps --doc --each-feature
  udeps:
    name: Check rp2040-hal for unused dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-30
          target: thumbv6m-none-eabi
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Install cargo-udeps
        run: |
          curl -sSL https://github.com/est31/cargo-udeps/releases/download/v0.1.45/cargo-udeps-v0.1.45-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - --strip-components=2 -C ~/.cargo/bin ./cargo-udeps-v0.1.45-x86_64-unknown-linux-gnu/cargo-udeps
      - name: Check unused deps in rp2040-hal
        run: cd rp2040-hal && cargo hack udeps --optional-deps --each-feature --target=thumbv6m-none-eabi
      - name: Check unused deps in rp2040-hal-macros
        run: cd rp2040-hal-macros && cargo hack udeps --optional-deps --each-feature
      - name: Check unused deps in rp2040-hal-examples
        run: cd rp2040-hal-examples && cargo hack udeps --optional-deps --each-feature
      - name: Check unused deps in on-target-tests
        run: cd on-target-tests && cargo hack udeps --optional-deps --each-feature
  msrv:
    name: Verify build on MSRV
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77
          target: thumbv6m-none-eabi
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Use older version of regex
        run: cd rp2040-hal-examples && cargo update -p regex --precise 1.9.3
      - name: Build rp2040-hal (on MSRV)
        run: cd rp2040-hal && cargo hack build --optional-deps --each-feature --target=thumbv6m-none-eabi
      - name: Build rp2040-hal-macros (on MSRV)
        run: cd rp2040-hal-macros && cargo hack build --optional-deps --each-feature
      - name: Build on-target-tests (on MSRV)
        run: cd on-target-tests && cargo hack build --optional-deps --each-feature
      - name: Build rp2040-hal-examples (on MSRV)
        run: cd rp2040-hal-examples && cargo hack build --optional-deps --each-feature
